### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by ivansalgado22** [AJ-TechSoul/ELECTRON-4-PHP#6]
Hi.
I'm testing this application for the Electron framework and I liked it a lot.

I wanted to know if it is possible to use ELECTRON-4-PHP to carry out a project with commercial purpose.
Thank you.

**Comment by AJ-TechSoul** [comment]
Yes as per the license you can use for commercial purpose also but please do the testing because for now it works well in MacOS and Windows(not confirmed fully for windows), but later we are planning to support it to windows and linux greatly. I even want some people to help me in this project. I want the one who is good in Javascript and node.

**Comment by ivansalgado22** [comment]
Thanks for your answer.
I was testing it on windows 10 and for now I had no problem. Then I will try it in windows 8.1 and 7.

**Comment by AJ-TechSoul** [comment]
Great !!! Thanks for your reply, it was informative.
